# Generated by Django 2.1.7 on 2019-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='testt_text',
            field=models.CharField(default='nullss', max_length=200),
        ),
    ]
