# Generated by Django 2.1.7 on 2019-02-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_testt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='testt_text',
        ),
    ]
